url: https://jclouds.apache.org
title: Apache jclouds
markdown: rdiscount
pygments: true
paginate: 5
paginate_path: "blog/page:num"
permalink: /blog/:categories/:year/:month/:day/:title
relative_permalinks: false
latest_version: 2.0.0
latest_version_date: 2016-11-15
latest_snapshot: 2.1.0-SNAPSHOT
